services:
  - type: web
    name: ventas-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    rootDir: backend
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
